---
- name: Start Reboot on Multiple Windows Systems and Disconnect
  hosts: win
  gather_facts: no  # Disable facts gathering to speed up the playbook

  tasks:
    - name: Schedule Reboot on Windows Systems
      win_command: Restart-Computer -Force
      async: 3600  # Set a long async timeout to give each system time to reboot
      poll: 0
      register: reboot_tasks  # Register the task IDs for all reboots
      async_timeout: 30  # Set a timeout for the initial task to disconnect after 30 seconds

    - name: Disconnect from Reboot Tasks
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ reboot_tasks.results }}"
      async_timeout: 30  # Set a timeout for the async_status task to disconnect after 30 seconds

